### ISSUE TITLE
Search UI has horizontal overflow

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-search#14]
This is hard to get an image of, but if you are scrolling through content on desktop or mobile, the interior of the search modal shifts a bit from left to right. I've seen this in RR and NDBOOKS.

**Comment by regisphilibert** [comment]
The pagination was not wrapping, hence overflowing its parent. Added `flex-wrap` plus some minor aesthetical adjusments to accomodate small screens.
