### ISSUE TITLE
If possible, add "preconnect" for Algolia

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-search#9]
When you using Algolia, we should use 

`<link rel="preconnect" href="https://ALGOLIA_APP_ID-dsn.algolia.net/" crossorigin>`

In the head of our sites. If we can automate this, it would be good for performance.

**Comment by regisphilibert** [comment]
@budparr for websites were a search script would not be loaded on every page, should that preconnect tag be on every pages or only the one with the search script.

**Comment by budparr** [comment]
Good question. I'd guess it be safe to load it anytime the Algolia/Search script itself is loaded? Does that make sense?
